version: '3.7'

services:

  api:
    image: node:14
    working_dir: /app
    volumes:
      - ..:/app
    environment:
      - PORT=3000
      - POSTGRES_DB=whosaidtrue-dev
      - POSTGRES_HOST=whosaidtrue-dev.czir8qxpg0qe.us-east-2.rds.amazonaws.com
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - JWT_SECRET=mySecret
      - DB_POOL_MIN=1
      - DB_POOL_MAX=5
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@whosaidtrue-dev.czir8qxpg0qe.us-east-2.rds.amazonaws.com:5432/whosaidtrue-dev
    ports:
      - 3000:3000

