version: '3.7'

services:

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  pgadmin:
    extends:
      file: docker-compose.yml
      service: pgadmin

  api:
    build:
      context: .
      target: api
    image: whosaidtrue/api
    container_name: api
    restart: always
    env_file:
      - .local.env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - 4000:4000

    depends_on:
      - postgres

  socket-server:
    build:
      context: .
      target: socket-server
    image: whosaidtrue/socket-server
    container_name: socket-server
    restart: always
    env_file:
      - .local.env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - 4001:4001

    depends_on:
      - postgres

# named volume to help identify db data volume
volumes: 
  data:
  pgadmin-data: