version: '3.7'

services:

  redis:
    image: redis:6.0
    container_name: wst-redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  postgres:
    image: postgres:11
    container_name: wst-postgres
    env_file:
      - .docker.env
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../apps/database/dev:/usr/local/dev # Used to facilitate running sql files from host. See database README

  
# named volume to help identify db data volume
volumes: 
  postgres-data:
