import { Pool } from 'pg';
import format from 'pg-format';

const phrases = [
    "A nod’s as good as a wink to a blind horse",
    "A penny saved is a penny and a half earned (taxes)",
    "Art decorates space. Music decorates time",
    "Baby ducks are cute",
    "Be in the moment",
    "Breathe through your eyelids",
    "Buckle up buttercup",
    "Buckle up, it's going to be a bumpy night",
    "Candlesticks always make a nice gift",
    "Carpe diem",
    "Chill Phil",
    "Chillax my friend",
    "Cool your jets, Fritz",
    "Dear Future, I'm ready",
    "Dearly beloved, we have gathered here today",
    "Dieting is eating food that makes you sad",
    "Do you have the time to listen to me whine",
    "Do you believe in miracles",
    "Don't try to fit in if you were born to stand out",
    "Don't go chasing waterfalls",
    "Eating a whole bag of Doritos begins with one chip",
    "Enjoy the laughs",
    "Every stick has two ends",
    "Everything is AWESOME!",
    "Everything not saved will be lost",
    "Feel electric tonight",
    "Fortune favors the bold",
    "Get up and do the robot",
    "Get on the floor and do the worm",
    "Good beginning make good endings",
    "Go ahead, be gone with it",
    "Go ahead, Make my day",
    "Hasta la vista, baby",
    "Here's looking at you kid",
    "Hold your horses Henry",
    "I coulda been a contender",
    "I have a feeling we're not in Kansas anymore",
    "I like big books and I cannot lie",
    "I love not camping",
    "I may be wrong, but I'm never uncertain",
    "I saw a werewolf with a Chinese menu in his hand",
    "If a panther should knock, don't anther",
    "If you tell it, they will laugh",
    "I'm serious. And don't call me Shirley",
    "It's a cakewalk",
    "It's all uphill (or downhill) from here",
    "It's about the stories, not the points",
    "It's about the stories, not the score",
    "It's just a flesh wound",
    "It's like déjà vu all over again",
    "It's not rocket science",
    "It's probably Dave. It's always Dave",
    "He who puts up with insults invites injury",
    "He eats shoots and leaves",
    "Hello darkness, my old friend...",
    "Hello? Is there anybody in there?",
    "Hum along.  Taking it easy...",
    "Humor is tragedy plus time",
    "Humor is life's greatest blessing",
    "Just breathe",
    "Keep your friends close",
    "Kick back and put your feet up",
    "Laughter is the best medicine",
    "Life is a banquet. Don't fill up on bread",
    "Life is good",
    "Life is far too important to be taken seriously",
    "Lighten up Francis",
    "Let my love open the door",
    "Let your hair down",
    "Let your mind wander",
    "Let yourself go",
    "Loosen up!",
    "Love is the answer",
    "Make an offer he can't refuse",
    "May the Force be with you",
    "Mellow fellow",
    "Mmmmm...donuts",
    "My name's Bond. James Bond",
    "Never answer an anonymous letter",
    "Nobody puts Baby in a corner",
    "Nothing hard is ever easy",
    "Now the future",
    "Oh, the thinks you can think!",
    "Ommmmmmmm...",
    "Only you can control your future",
    "Ooga-chaka, Ooga-ooga, Ooga-chaka",
    "Ob-la-di ob-la-da life goes on bra",
    "Order a drink",
    "Piece of cake",
    "Please excuse me while I kiss the sky",
    "Pour a little sugar on me",
    "Put your feet up",
    "Relax and enjoy the laughs",
    "Relax your shoulders",
    "Relax. Make yourself at home",
    "Remember, nobody's perfect",
    "Saying \"I'm sorry\" is life's best cheat code",
    "Seize the day. Make your lives extraordinary",
    "Shaken, not stirred",
    "Show me the money!",
    "Simple is best",
    "Smell that?!",
    "Spill the beans",
    "Stop! Hammer time!",
    "Streeetttccchhh",
    "Surely you can't be serious",
    "Take a breather",
    "Take a chill pill, Bill",
    "Take a load off",
    "Take a pew",
    "Take it easy, Weezy",
    "That rug really ties the room together",
    "The answer my friends is blowing in the wind",
    "The future ain't what it used to be",
    "The stillness is the move",
    "The world is a vampire",
    "There must be some kinda way out of here",
    "There's no crying in baseball",
    "Think and wonder, wonder and think",
    "This is the beginning of a beautiful friendship",
    "Time is the fire in which we burn",
    "'Tis better to know how to learn than to know",
    "Toga! Toga!",
    "Viva La Vida",
    "Wastin' away again in Margaritaville",
    "Well-behaved women rarely make history",
    "We're gonna need a bigger boat",
    "What we've got is a failure to communicate",
    "When you come to a fork in the road, take it",
    "You are you more than anyone else",
    "You can observe a lot by watching",
    "You can't handle the truth!",
    "You finished fast. Here is a pony",
    "You had me at Hello",
    "You look good on the dance floor",
    "You talking to me",
    "You're fast. Have a cookie",
    "You're gorgeous!",
    "You’re in pretty good shape for the shape you are in",
    "Your friends are the family you pick",
    "Young hearts run free"
]

export function insertOneLiners(pool: Pool) {

    const phrasesWithClean = phrases.map((phrase, index) => {
        return [phrase, index % 2 === 0];
    })
    const query = {
        text: format(`
            INSERT INTO one_liners (text, clean)
            VALUES %L
        `, phrasesWithClean)

    }

    return pool.query(query);
}